=== brunomaroneze/dicbio/data/corpus.dtd
<!ELEMENT text (front, body, back)>
 <!ATTLIST text author CDATA #REQUIRED>
 <!ATTLIST text title CDATA #REQUIRED>
 <!ATTLIST text date CDATA #REQUIRED>
<!ELEMENT front (#PCDATA|title|p|s|pb|note|foreign)*>
<!ELEMENT body (#PCDATA|title|p|s|pb|note|foreign)*>
<!ELEMENT back (#PCDATA|p|s|pb|note|foreign)*>
<!ELEMENT title (#PCDATA|s|note|pb|foreign)*>
 <!ATTLIST title type (main|sub) #IMPLIED>
<!ELEMENT p (#PCDATA|s|note|pb|foreign)*>
<!ELEMENT s (#PCDATA|w|term|note|pb|foreign)*>
<!ELEMENT w (#PCDATA)>
 <!ATTLIST w synonym CDATA #IMPLIED>
 <!ATTLIST w norm CDATA #IMPLIED>
 <!ATTLIST w orig CDATA #IMPLIED>
<!ELEMENT pb EMPTY>
 <!ATTLIST pb n CDATA #REQUIRED>
<!ELEMENT term (#PCDATA)>
 <!ATTLIST term lemma CDATA #IMPLIED>
 <!ATTLIST term norm CDATA #IMPLIED>
 <!ATTLIST term msd CDATA #IMPLIED>
 <!ATTLIST term senseNumber CDATA #IMPLIED>
<!ELEMENT note (#PCDATA|s|p|pb|foreign)*>
<!ELEMENT foreign (#PCDATA)>
<!ATTLIST foreign lang CDATA #REQUIRED>

=== brunomaroneze/dicbio/data/compendio2brotero.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE text SYSTEM "corpus.dtd">
<text author="BROTERO, Felix Avellar" title="Compendio de Botanica" date="1788">
    <front>COMPENDIO DE BOTANICA, OU NOÇOENS ELEMENTARES DESTA SCIENCIA, segundo os melhores
        Escritores modernos, expostas na lingua Portugueza, Por FELIX AVELLAR BROTERO. TOMO SEGUNDO. <foreign
            lang="latim">Nisi in ordines redigantur Plantae et velut castrorum acies destribuantur
        in suas classes, omnia fluctuari necesse est. Caesalp.</foreign> PARIS. Vende-se em Lisboa,
        em caza de PAULO MARTIN, Mercador de Livros. M,DCC,LXXXVIII.</front>
    <body><pb n="3" /> EXPOSIÇAÕ DO SYSTEMA SEXUAL. CAPITULO I. Do Systema de Linneo, e das suas
        Classes e Ordens em geral. <p>O engenhoso Systema de Linneo, cuja exposiçaõ deve occupar o
        primeiro lugar deste Volume, he fundado nos organos sexuaes das flores, e dirigido a classar
        todos os modos, com que elles podem existir nos vegetaes: esta foy a razaõ porque o seu
        autor lhe deo o nome de Systema Sexual (Systema Sexuale). Cada hum destes differentes modos
        reune hum certo numero de relaçoẽs geraes, gradativamente deduzidas da Florecencia, e nesta
        reuniaõ he que foraõ estabelecidas as vinte e quatro classes, de que se compoem o dicto
        Systema.</p> A Florecencia de todos os vegetaes conhecidos ou he bem destinctamente visivel
        ou he clandestina. Na que he bem destinctamente visivel, os organos sexuaes saõ assaz
        apparentes sem o soccorro do microscopio de maneira que ninguem os confundirà jamais nem com
        as sementes nem com o tenro fructo. As <pb n="4" />plantas, cuja Florecencia he bem
        destinctamente visivel, humas daõ na mesma especie flores todas hermaphroditas, outras daõ
        flores masculinas e femininas taõbem na mesma especie: no primeiro cazo as flores
        hermaphroditas ou tem os estames desapegados entre si e juntamente do pistillo<note>Naõ
        saõ insertos ao pistillo, mas sim ao receptaculo, calys, ou corolla; e saõ soltos, isto he,
        tem os filetes desadunados e igualmente as antheras.</note>, ou apegados entre si ou ao
        pistillo<note>Isto he, insertos ao pistillo, ou parte equivalente a elle.</note> Se os
        estames se achaõ desapegados, e saõ de comprimento inderterminado<note>Isto he, quando
        dois delles naõ saõ sempre mais curtos nas flores de quatro e seis estames; e nas demais,
        quando variaõ muito no comprimento na mesma especie ou individuo, sendo ora todos iguaes,
        ora hum mais baxo, ora tres mais altos, &amp;c. e as vezes huns mais curtos outros mais altos
        alternadamente como na Daphne.</note>, constituem as treze primeiras classes, que differem
        humas das outras pelo numero dos dictos estames, e seu lugar de insersaõ<note>Isto he, pelo
        apego da base do filete ao calys ou receptaculo.</note>. Na 1ª. classe ou Monandria<note>Os
        que dezejarem saber as etymologias Gregas dos nomes das Classes e Ordens podem consultar o
        Diccionario dos termos botanicos que ajuntei no fim deste Compendio.</note> as flores
        constaõ de hum so estame, na 2ª. ou Diandria constaõ de dois, na 3ª. ou Triandria de tres,
        na 4ª. ou Tetrandria de quatro, na 5ª. ou Pentrandria de cinco, na 6ª. ou Hexandria de seis,
        na 7ª. ou Heptandria de sette, na 8ª. ou Octandria de oito, na 9ª. ou Enneandria de nove, na
        10ª. ou Decandria de dez, na 11ª. ou Dodecandria de onze athe dezanove inclusivamente, na
        12ª. ou Icosandria de vinte ou mais insertos ao calyz, na 13ª. ou Polyandria de numerosos </body>
    <back></back>
</text>
